{% set name = "precession" %}
{% set version = "2.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9b420843cdca603bc3cadfad49fc21b570f133e75de663437666b870398941cf

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - parmap >=1.5.1
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - precession
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: "https://github.com/dgerosa/precession/"
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.txt
  summary: "Dynamics of precessing black-hole binaries"
  doc_url: https://pypi.org/project/precession/
  dev_url: https://github.com/dgerosa/precession/

extra:
  recipe-maintainers:
    - chadhenshaw
